spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        druid:
            master-data-source:  #主库数据源
#              url: jdbc:mysql://192.168.12.69:3310/mcsports_platform?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
              url: jdbc:mysql://localhost:3306/poker_dictionary?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#              username: mcs_dev
#              password: VGeKpDmzhEw=
              username: root
              password: 123456
            slaveDataSource:  #从库数据源
              url: jdbc:mysql://localhost:3306/poker_dictionary?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#              username: mcs_dev
#              password: VGeKpDmzhEw=
              username: root
              password: 123456
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /druid/*
                #login-username: admin
                #login-password: admin
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true


#图片上传配置
upload: 
  uploadMap:
    cmsArticlePath: /home/photo/
    cmsArticleUrl: /
  pictureIP: http://39.106.153.108:80


#sftp上传配置(测试)
sftp:
  config:
    server: 39.106.153.108
    port: 22
    user: root
    password: nX$v@4kLUXF675


#登陆链接http://208.109.11.123:80
poker:
  url: http://www.poker-dictionary.net/wp-login.php
